name: "Gatsby Cloud ENV Update"
description: "Update the ENV of Gatsby Cloud"
inputs:
  gatsby-token:
    description: "The token used to access Gatsby Cloud"
    required: true
  gatsby-site-id:
    description: "The Gatsby Cloud site ID"
    required: true
  terraform-output:
    description: "The terraform output as a JSON file"
    required: true
outputs:
  BUILD:
    description: "Whether the build ENV was updated"
  PREVIEW:
    description: "Whether the preview ENV was updated"
runs:
  using: "node12"
  main: "index.js"
