name: "Gatsby Cloud ENV Update"
description: "Update the ENV of Gatsby Cloud"
inputs:
  GATSBY_TOKEN:
    description: "The token used to access Gatsby Cloud"
    required: true
  GATSBY_SITE_ID:
    description: "The Gatsby Cloud site ID"
    required: true
  TERRAFORM_OUTPUT:
    description: "The terraform output as a JSON file"
    required: true
outputs:
  BUILD:
    description: "Whether the build ENV was updated"
  PREVIEW:
    description: "Whether the preview ENV was updated"
runs:
  using: "node12"
  main: "index.js"
