on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: tnorlund/gatsby-cloud-action@v1.0.5
      with:
        GATSBY_TOKEN: ${{ secrets.GATSBY-TOKEN }}
        GATSBY_SITE_ID: ${{ secrets.GATSBY-SITE-ID }}
        TERRAFORM_OUTPUT: terraform/output.json